### ISSUE TITLE
Files cannot be loaded

### ISSUE THREAD

**Issue by siredmar** [stwe/Benno#2]
As you are working on Windows you don't have the problem with inconsistent cased file naming. 
For this i implemented the files class in mdcii:
https://github.com/siredmar/mdcii-engine/blob/master/source/mdcii/mdcii/src/files/files.cpp
https://github.com/siredmar/mdcii-engine/blob/master/source/mdcii/mdcii/include/mdcii/files/files.hpp
It would be nice if Benno had some sort of file handling as well to eliminate naming issues for those files.

**Comment by stwe** [comment]
That's on the way. However, a little different from your solution. My goal was to no longer have to specify filenames/strings in the methods. All files and their names are known. So these names are converted into constants and collected in Enums. It was also important to me that the zoom can be specified at the same time.

This can be used as follows:

```cpp
    m_paletteFile = std::make_unique<file::PaletteFile>(m_files.GetColFile().path);
    m_paletteFile->ReadContentFromChunkData();

    auto stadtfldFile{ m_files.GetBshFile(gameOptions.currentZoomId, file::BshFile::BshFileNameId::STADTFLD).value() };
    m_bshFile = std::make_unique<file::BshFile>(stadtfldFile.path, m_paletteFile->GetPalette());
    m_bshFile->ReadContentFromChunkData();
```

**Comment by siredmar** [comment]
I like the idea!
We can do several classes for each file type like you already did for PaletteFile and BshFile, e.g. for Cod FIles, Gad Files, etc..

**Comment by siredmar** [comment]
We need to make sure that this file class also works for non windows systems.

**Comment by stwe** [comment]
It worked for me yesterday with Mint 20. Can you give me the error message?

**Comment by siredmar** [comment]
Oh, i didn't try it out. I just saw in the code that there was a reference to some Windows drive label...

**Comment by stwe** [comment]
Yes change the path to: `/home/armin/your_path_to_anno`

**Comment by stwe** [comment]
All files are loaded.
