### ISSUE TITLE
GUI System

### ISSUE THREAD

**Issue by siredmar** [stwe/Benno#4]
We need a GUI system to interact with the user. 
This Issue can work as starting point for gui specifications and be split up for each 'widget'.
Basic requirements are:

**Basic layouting:**
- can be placed arbitrarily
- size can be defined arbitrarily
- V-Box
- H-Box
- Grid
- All together combined
- boxes/grids can contain other widgets or layouts
- can be defined const in size or dynamically when window is resized

**Image:**
- can be placed arbitrarily
- size can be defined arbitrarily
- can load a BSH image

**Buttons:**
- size can be defined arbitrarily
- can be placed arbitrarily
- can load a BSH image in clicked states
- can load a second BSH image in unclicked states
- callback or signal/slot for: hover(state), clicked(state)
- uses the secondary image if clicked or hovered, uses primary image if unclicked or not hovered

**Text entry:**
- can be placed arbitrarily
- size can be defined arbitrarily
- can load a BSH image as background
- can be set a default value
- has a maximum string length
- Text color customizable
- Text shadow customizable
- Text size customizable
- Text font chosable
- Can work with **.zei** font files
- callback or signal/slot for: clicked(state), finished(), input(text) 

**Table:**
- can be placed arbitrarily
- size can be defined arbitrarily
- dynamic adding and removing of elements
- can load a BSH image as background
- can be set a default value
- has a maximum string length
- can contain 
- Text color customizable
- Text shadow customizable
- Text size customizable
- Text font chosable
- Can work with **.zei** font files
- callback or signal/slot for: clicked(element, state), hover(element, state)
- can be scrollable with mousewheel and/or slider widget

**Tabs Menu:**
- can be placed arbitrarily
- size can be defined arbitrarily
- can contain other widgets/layouts
- initialized with specific amount of elements
- tabs can load a BSH image in clicked states
- tabs can load a second BSH image in unclicked states
- callback or signal/slot for: hover(tab, state), clicked(tab, state)
- uses the secondary image if clicked or hovered, uses primary image if unclicked or not hovered

**Multiline Label:**
- can be placed arbitrarily
- size can be defined arbitrarily
- value can be set dynamically
- default value can be set
- callback or signal/slot for: clicked(state), hover(state)
- can be scrollable with mousewheel and/or slider widget

**Slider:**
- can be placed arbitrarily
- size can be defined arbitrarily
- can load BSH image for moving slider 
- can load BSH image as background
- can be attached to table or multiline label
- callback or signal/slot for: slide(percent)
- customizable resolution (default 100)

**Comment by stwe** [comment]
@siredmar Have you had a look at ImGu (https://github.com/ocornut/imgui)i? This is not nice, but it is very useful for debugging and quickly integrated. I have already uploaded the necessary files.

Otherwise it sounds like a lot of work ...

**Comment by stwe** [comment]
After I pressed the F5 key in my Visual Studio IDE.....

look at this...

Use your mouse on a ImGui slider to show all the Stadtfld textures. Pretty cool!! 

![Slider](https://user-images.githubusercontent.com/2964748/98869557-42c4d680-2472-11eb-9113-7afb56ba3b55.png)

**Comment by siredmar** [comment]
I really like this! I took a quick look at imgui. I guess it gives all requested things, at least with some custom widgets based!
Nice!
